### ISSUE TITLE
Provide preconnect connection count hint

### ISSUE THREAD

**Issue by pmeenan** [w3c/resource-hints#24]
I'm in the process of implementing preconnect for Chrome (currently enabled behind a flag) but am bumping into an issue around determining the number of connections to open for a request.  The user agent doesn't have the context it needs to know how many requests a developer may be issuing for a given href.

There are a good number of cases where the dev only wants to preconnect for a single request (beacons, redirect servers, ad servers, etc) but there are also a lot of cases where they would like to open as many as possible for upcoming images (CDNs serving static resources are a prime case).

The user agent should be able to determine how many actual connections get opened depending on the factors mentioned in the spec but it needs a hint as to how many it will likely need.

The initial implementation hacks around this by incrementing the connection count for every preconnect link tag but that is a pretty ugly hack, causes delays in the preconnecting and breaks down when we add logic to the preload scanner to parse the preconnect requests.

We can engineer around most of the issues but it would be really good to have a specified mechanism for developers to indicate "one" vs "a lot".  Separate directives would be really easy - "preconnect" vs "preconnect-multiple" or a new attribute on the link tag that carries the likely resource count (none of the existing attributes make sense for overloading with that data).

**Comment by pmeenan** [comment]
Using a different rel attribute for indicating multiple also makes for a clean HTTP header implementation without changing the format of the Link header (more likely to be backward compatible though it may not be that big of a deal).

**Comment by yoavweiss** [comment]
:+1:

I don't think there's a problem with adding a separate attribute here, since we already defined a bunch of those.

**Comment by igrigorik** [comment]
> There are a good number of cases where the dev only wants to preconnect for a single request (beacons, redirect servers, ad servers, etc) but there are also a lot of cases where they would like to open as many as possible for upcoming images (CDNs serving static resources are a prime case).

I think we're finding that "as many as possible" is, in fact, an anti-pattern in precisely those cases where developers tend to think it will help the most (high latency). The [etsy oversharding case study](http://perf.fail/post/96104709544/zealous-sharding-hurts-etsy-performance) comes to mind, and I think [Will's recommendation](https://insouciant.org/tech/network-congestion-and-web-browsing/) is on point: 

> _"Web developers using high amounts of domain sharding to work around low connection per host limits in old browser should reconsider their number of shards for newer browsers. Anything over 2 is probably too much, unless most of your user base is using older browsers."_

Also, the fact that Chrome has own heuristics for limiting number of parallel image downloads (regardless of number of connections) also indicates that the "number" is not a useful signal.

> The user agent should be able to determine how many actual connections get opened depending on the factors mentioned in the spec but it needs a hint as to how many it will likely need.

So, the underlying issue is: the developer knows if number of resources on this origin is "small", or "large". However, mapping small/large to number of connections is impossible to get right: the optimal number depends on client's properties like latency, BW, negotiated protocol, etc. With that in mind...

Personally, I think we want to steer clear of exposing "number of connections" as an explicit primitive, as its a great way to shoot yourself in the foot, and it's an anti-pattern / no-op under HTTP/2. Also, if the "optimal" number in most cases is, in fact, 2 connections (for HTTP/1.X), then it seems like we should just do that instead... which is our existing behavior anyway.

I'm wondering if the following behavior would be sufficient:
- If preconnect is specified to a previously unknown origin: open two connections.
- If preconnect is specified to a seen origin, used past data to open "optimal" number.
  - For HTTP/2 the number is 1.
  - For HTTP/1.X the number depends on number of resources _and_ users connectivity profile.

**Comment by pmeenan** [comment]
Even the difference between "1" and "more than one" would be a very helpful signal and in a lot of cases opening 2 connections may be a bad decision.  For example, wikipedia uses a dns-prefetch hint for their beacon server meta.wikimedia.org ([request #30 here](http://www.webpagetest.org/result/150212_7M_79c435f37f51beb46cddc57ab7fecc76/1/details/)).  If they were to provide a preconnect hint then Chrome would open twice as many connections to the beacon server as would actually be needed.

Maybe it's not really a big deal in practice but always consuming 2x the needed file descriptors on the server seems wasteful if the dev knows there will only ever be one request at a time to this domain.

The preconnect directive exists mostly for cases where the UA doesn't have history or knowledge to make intelligent decisions about what will be needed, otherwise we'll just use the existing history-based predictor logic.

**Comment by pmeenan** [comment]
I'm also not recommending that the dev be able to request a specific number of connections, just to be able to tell the browser how many requests are likely going to be coming from the given server.  It is up to the UA to decide what to do with that information.

In the case of Chrome, we will continue to:
- Not open more than 1 connection if we know the server will be talking SPDY or HTTP/2 based on past history
- Schedule resource fetches as we determine is appropriate

**Comment by igrigorik** [comment]
> Maybe it's not really a big deal in practice but always consuming 2x the needed file descriptors on the server seems wasteful if the dev knows there will only ever be one request at a time to this domain.

That would only be the case for origins which we have not seen before. Otherwise I would expect the UA to remember how many connections it used on previous attempt (as Chrome already does today) and open the "appropriate" number of connections. As such, I think this is a fairly well contained.

> The preconnect directive exists mostly for cases where the UA doesn't have history or knowledge to make intelligent decisions about what will be needed, otherwise we'll just use the existing history-based predictor logic

That's definitely an important use case, but it's not the only one. For example, [redirects](http://w3c.github.io/resource-hints/#anonymizing-redirect-preconnect) is not something that you can use your past nav history on.. and we have clients (e.g. G+) that want to use it to optimize load latency of target pages.

**Comment by pmeenan** [comment]
I'm pretty sure Chrome's predictor history is for pages, not origins so it tracks the number of connections needed for each origin for pages on a given domain but not for the origin in isolation.  i.e. if I see an omniture preconnect on a page that I've never visited even if I have seen lots of other pages that make requests to the same domain I don't know how many requests this page is going to make.

That's an implementation detail though and we could start adding per-origin connection count history to a global tracking database, it just doesn't exist right now and probably won't for a while.

**Comment by igrigorik** [comment]
> I'm pretty sure Chrome's predictor history is for pages, not origins so it tracks the number of connections needed for each origin for pages on a given domain but not for the origin in isolation. i.e. if I see an omniture preconnect on a page that I've never visited even if I have seen lots of other pages that make requests to the same domain I don't know how many requests this page is going to make.

We do track subresource hosts, number of resources, and connections and it works [pretty darn well](https://code.google.com/p/chromium/issues/detail?id=449224#c8)! :) For example, results for gist.github.com from my own chrome://dns:
![image](https://cloud.githubusercontent.com/assets/10652/6177913/2d59bbba-b2bf-11e4-848e-3ff378580351.png)

---

I think we agree that exposing "number of connections" is not a great idea. Now, for sake of an argument, let's say we have two variants (a) rel=preconnect, (b) rel=preconnect-many. The syntax is not important, but the key insight is that sometimes you just want to signal to the UA that it might want to open multiple connections. Assuming I have that, the developers decision tree is:

![image](https://cloud.githubusercontent.com/assets/10652/6178311/7f056178-b2c2-11e4-9ffd-c4f40b176575.png)

The boxes in yellow need to be decided at runtime by the browser. As such, the **only win** here is that developer can hint the UA to open 1 instead of 2 connections for first visit scenario... since on repeat visit the difference between preconnect and preconnect-many is no longer relevant because UA remembers stats from past visit. 

Given the small benefit, I'm not convinced we need to complicate this for developers or implementers: 
- On first visit, if no data is available: start with 2 connections if HTTP/1.x, and 1 if HTTP/2.
- On repeat visit use past stats and/or other runtime data (quality / type of connection).

The above flow removes the burden from the developer completely and keep things simple - i.e. there is only rel=preconnect. Yes, there is a bit of "overhead" for cases where only a few resources are fetched and we end up doing an extra handshake on first visit.. but that's the exact behavior that current browsers implement today anyway - nothing new.

Or, am I still barking up the wrong tree? :)

**Comment by pmeenan** [comment]
The predictor information you are looking at is for visiting a page on https://gist.github.com/

What we don't track is the connection information for the subresources independent of the hosting page (i.e. for pages where we see requests for avatars0.githubusercontent.com, how many connections to that subresource are usually needed).  And by that I mean is http://amazon.com/, http://msn.com/ etc all reference the same shared resource.

Think something like the google analytics beacon server.  If you visit www.webpagetest.org frequently we will learn that you need one connection to www.google-analytics.com.

If you then visit blog.patrickmeenan.com and see a preconnect hint for www.google-analytics.com we have no history or context for blog.patrickmeenan.com and don't know how many connections you are going to need.  Since we don't track the average connection count for www.google-analytics.com by itself, just in the context of pages that refer to it we don't have anything to base a decision on for how many connections to open.

If we default to 2 when we have no history then we will open 2 connections to every domain that uses GA the first time we visit it regardless of how many other pages we have visited that use GA, even though only one will ever be needed.

Your logic tree above is accurate though in the many case N could be max instead of 2 :-) and if it is a new attribute with an actual number of resources likely to be needed then the developer could be providing input on what N should be if more than one gets opened.

I think preconnect will be useful for a lot of the beaconing/tagging solutions to help get the beacons delivered sooner (which usually means more reliably) and it could be self contained where the js adds the preconnect tag for a request that will fire at a later point.

**Comment by igrigorik** [comment]
> If you then visit blog.patrickmeenan.com and see a preconnect hint for www.google-analytics.com we have no history or context for blog.patrickmeenan.com and don't know how many connections you are going to need.

Yes, which to me, is the correct behavior. Just because some other site only needed one connection to a third party doesn't mean the other origin will have the same usage pattern. Perhaps it would be interesting to build a "global" view to help improve the first-visit case... but that's just an example of automated optimization that browsers could/should implement to further improve rel=preconnect for first-visit cases?

> If we default to 2 when we have no history then we will open 2 connections to every domain that uses GA the first time we visit it regardless of how many other pages we have visited that use GA, even though only one will ever be needed.

Right, which AFAIK, is exactly what some browsers do already - e.g. IE? 

> Your logic tree above is accurate though in the many case N could be max instead of 2 :-) and if it is a new attribute with an actual number of resources likely to be needed then the developer could be providing input on what N should be if more than one gets opened.

But N is dependent on client's state. I think we're completely overlooking the congestion / retransmit problem.. I'm extremely vary of providing a knob that says "open N" and then either (a) not opening N and having developers complain that we're breaking contract, and/or (b) cause tons of retransmit and congestion.. because most developers will simply set it to some arbitrary high number.

---

To be clear, I'm all for exposing more developer control... But in this particular instance I'm just getting hung up on the fact that it's a knob that seems to introduce more misdirection and confusion than actual value... =/

_P.S. I know not everyone finds this a compelling argument but... Personally I _am_ inclined to provide incentives to developers to migrate towards newer and better infrastructure, instead of trying to patch the old-and-broken and in the process add unnecessary complexity to the whole system.. In this instance, this entire discussion is a no-op for HTTP/2. So, one potential answer to "but what if I want to fetch many resources" is: use HTTP/2._

**Comment by yoavweiss** [comment]
On Fri, Feb 13, 2015 at 4:34 AM, Ilya Grigorik notifications@github.com
wrote:

> If we default to 2 when we have no history then we will open 2 connections
> to every domain that uses GA the first time we visit it regardless of how
> many other pages we have visited that use GA, even though only one will
> ever be needed.
> 
> Right, which AFAIK, is exactly what some browsers do already - e.g. IE?
> 
> Yeah, but 2 (in an HTTP1 world) is almost never the right answer. We can
> try to run the numbers over the HTTPArchive, but my money is on it being
> wrong >80% of the time.
> 
>  Your logic tree above is accurate though in the many case N could be max
> instead of 2 :-) and if it is a new attribute with an actual number of
> resources likely to be needed then the developer could be providing input
> on what N should be if more than one gets opened.
> 
> But N is dependent on client's state. I think we're completely overlooking
> the congestion / retransmit problem.. I'm extremely vary of providing a
> knob that says "open N" and then either (a) not opening N and having
> developers complain that we're breaking contract, and/or (b) cause tons of
> retransmit and congestion.. because most developers will simply set it to
> some arbitrary high number.
> 
> I don't think anyone is arguing for an "open N connections" knob. What we
> can provide is a "how many resources? one/many" knob, and let the browser
> handle congestion heuristics (as well as past browsing heuristics) in
> determining how many connections it should open in the "many resources"
> case.

---

> _P.S. I know not everyone finds this a compelling argument but...
> Personally I am inclined to provide incentives to developers to migrate
> towards newer and better infrastructure, instead of trying to patch the
> old-and-broken and in the process add unnecessary complexity to the whole
> system.. In this instance, this entire discussion is a no-op for HTTP/2.
> So, one potential answer to "but what if I want to fetch many resources"
> is: use HTTP/2._
> 
> True, but unfortunately HTTP1 is not yet dead, and moving to TLS is not
> always simple. Why not add a property to make our behavior there better?

**Comment by pmeenan** [comment]
Most browsers will open 2 connections to the domain of the main resource of the page because it is highly likely that subresources from the same domain will be needed.  I don't think we can make the leap to assume the same pattern for subresources (for those browsers just open as many connections as they need).

Maybe it is best to keep it simple for now and see what people do with it and where the pain points are and evolve instead of trying to guess.  Chrome's initial implementation is only going to preconnect one connection.

**Comment by josephscott** [comment]
> Even the difference between "1" and "more than one" would be a very helpful signal and in a lot of cases opening 2 connections may be a bad decision.

I could see this being helpful.  If every site on WordPress.com declared a preconnect for something that we knew only needed one connection, it would be a waste to do anything more than that.  In a worse case situation it could result in millions of connections that never get used.

I'd lean towards an optional attribute that declares the "only 1 connection needed" case.  If the attribute isn't provided, then let the browser figure it out.

**Comment by igrigorik** [comment]
> Maybe it is best to keep it simple for now and see what people do with it and where the pain points are and evolve instead of trying to guess. Chrome's initial implementation is only going to preconnect one connection.

+1. Although, to clarify, one preconnect on first time we've observed that preconnect host. After the first time the UA will know the number of resources being fetched from that host and can automatically open an appropriate number of connections... And we can improve this "first view" logic further by leveraging connection stats from other hosts that may have connected to that origin in the past -- e.g. from other  sites the user has visited before, typically this origin needs ~2 connections.

**Comment by pmeenan** [comment]
Actually, one preconnect based on the link tag - no learning tied to the (preconnect) host as far as the link tag itself goes.

The normal heuristic-based preconnect logic will still be active so as we learn about the (page) host we will continue to open as many connections as we think will be needed.

There is no plan to crawl the prediction database for all (page) hosts that have connected to that origin and infer a likely number of connections from that (at least currently - it's something that could be done in the future if it looks like it makes sense).

```
<link rel="preconnect"...> = 1 connection, any other connection behavior is independent (for now anyway).
```

**Comment by igrigorik** [comment]
@pmeenan makes sense :+1:
