### ISSUE TITLE
Cross-origin prerender?

### ISSUE THREAD

**Issue by Krinkle** [w3c/resource-hints#43]
The current draft doesn't mention cross-origin restrictions on prerender. Presumably that means it is currently intended to allow for a site to prerender pages on any arbitrary domain.

There is a note about how one should use the Page Visibility API to delay/prevent certain actions from being taken. Such as analytics beacon, collection of Navigation Timing metrics, etc.

It is up to site administrators who adopt use of prerender to make sure their pages are prepared for this and account for any necessary changes in application logic and execution flow.

However I don't think we can reasonably expect all websites to proactively defend against this. We may want to consider potential abuse and security implications in this regard. For example, what if site A pre-renders site B without their knowledge. Could this cause a skew in their analytics or (as resources may be constrained) timing measures.

Existing relevant functionality:
- `X-Frame-Options` header. Sites can disallow (hidden) iframe embedding.
- `performance.navigation.type` (e.g. one can reject or separately collect timing measures for TYPE_RELOAD which can be very different from normal navigate views).

I haven't given it much thought yet, but perhaps prerender should honour the Same-origin policy, or X-Frame-Options, or be exposed as a special type in `performance.navigation.type`.

**Comment by igrigorik** [comment]
> However I don't think we can reasonably expect all websites to proactively defend against this. 

FWIW, I don't think "defend" is the right choice of word or way to look at this. Prerendering is part of the lifecycle of the page -- you don't "defend" against that, you **have to account for it.**
- Various browsers already leverage prerendering based on internal signals
- It's common for users to open background tabs without the content being visible (same result, really)

Regardless of `rel=preconnect`, you need to account for the above cases within your application, which is why we have the Page Visibility API.

> For example, what if site A pre-renders site B without their knowledge. Could this cause a skew in their analytics or (as resources may be constrained) timing measures.

Yes, which is why site B should use Page Visibility. AFAIK, most popular analytics vendors already account for this.

**Comment by yoavweiss** [comment]
Basically, we could have had either an opt-in mechanism for prerendering or an opt-out mechanism.
Currently, we have a rough opt-out mechanism using the visibility API. (enabling an "if the page is not visible, don't do X" logic)

The mechanisms you propose are also opt-outs AFAICT, but may offer a stricter policy (e.g. an "X-Frame-Options" may mean that nothing would be downloaded once the browser parses the opt-out header).

What are the advantages of such stricter mechanisms? What are you trying to prevent?

**Comment by igrigorik** [comment]
Closing. Please feel free to reopen if there is spec-related issues to work through here.
